[0;33m--- esp-idf-monitor 1.3.3 on /dev/ttyUSB0 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x4000c320: memcpy in ROM
[0m
[0;33m0x4000c2e0: memcpy in ROM
[0m
[0;33m0x4000c2f6: memcpy in ROM
[0m
[0;33m0x4000c31d: memcpy in ROM
[0m
[0;33m0x400dcc2f: jpeg_decode_in_cb at /home/alexander/esp/learn_japanese/managed_components/espressif__esp_jpeg/jpeg_decoder.c:132
[0m
[0;33m0x40061009: jd_prepare in ROM
[0m
[0;33m0x400dccb7: esp_jpeg_decode at /home/alexander/esp/learn_japanese/managed_components/espressif__esp_jpeg/jpeg_decoder.c:88
[0m
[0;33m0x400d67d8: decode_image_from_sd at /home/alexander/esp/learn_japanese/main/decode_image.c:130
[0m
[0;33m0x400d64cf: s_load_image at /home/alexander/esp/learn_japanese/main/memory.c:74
[0m
[0;33m0x400d66f8: init_background_image_from_sd at /home/alexander/esp/learn_japanese/main/display.c:33
[0m
[0;33m0x400d6042: app_main at /home/alexander/esp/learn_japanese/main/main.c:78
[0m
[0;33m0x400f61f8: main_task at /home/alexander/esp/esp-idf/components/freertos/app_startup.c:208
[0m
[0;33m0x40087475: vPortTaskWrapper at /home/alexander/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:137
[0m
[1;31mNone[0m
[0;33mWaiting for the device to reconnect[0mException in thread Thread-2 (_run_outer):
Traceback (most recent call last):
  File "/home/alexander/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 76, in run
    data = self.serial.read(self.serial.in_waiting or 1)
  File "/home/alexander/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexander/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 83, in run
    self.close_serial()
  File "/home/alexander/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 104, in close_serial
    self._disable_closing_wait_or_discard_data()
  File "/home/alexander/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 120, in _disable_closing_wait_or_discard_data
    buf = fcntl.ioctl(self.serial.fd, termios.TIOCGSERIAL, buf)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alexander/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/stoppable_thread.py", line 47, in _run_outer
    self.run()
  File "/home/alexander/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 100, in run
    self.close_serial()
  File "/home/alexander/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 104, in close_serial
    self._disable_closing_wait_or_discard_data()
  File "/home/alexander/.espressif/python_env/idf5.2_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 120, in _disable_closing_wait_or_discard_data
    buf = fcntl.ioctl(self.serial.fd, termios.TIOCGSERIAL, buf)
OSError: [Errno 5] Input/output error
[0m
